name: Criar APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Instalar dependências
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk wget
        pip install --upgrade pip
        pip install buildozer cython

    - name: Instalar o SDK do Android
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Aceitar licenças
      run: |
        yes | sdkmanager --licenses

    - name: Instalar SDK e Build Tools
      run: |
        sdkmanager --update
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Rodar Buildozer
      run: |
        buildozer -v android debug

    - name: Salvar APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
